// Typed wrappers over Folio's IPC commands. Payload types are generated from Rust
// (src-tauri/src/ipc.rs) by ts-rs; never edit ./generated by hand.
import { invoke } from '@tauri-apps/api/core';

import type { AppError } from './generated/AppError';
import type { DocumentInfo } from './generated/DocumentInfo';
import type { StartupTimings } from './generated/StartupTimings';

export type { AppError, DocumentInfo, StartupTimings };
export type { PageSize } from './generated/PageSize';

export function isAppError(value: unknown): value is AppError {
	return typeof value === 'object' && value !== null && 'message' in value;
}

export const openWithDialog = () => invoke<DocumentInfo | null>('open_with_dialog');
export const openStartupDocument = () => invoke<DocumentInfo | null>('open_startup_document');
export const closeDocument = (id: number) => invoke<void>('close_document', { id });
export const appReady = () => invoke<StartupTimings>('app_ready');
export const logMetric = (name: string, ms: number) => invoke<void>('log_metric', { name, ms });

/**
 * URL of a rendered page image. WebView2 (Windows) serves custom protocols as
 * http://<scheme>.localhost; other platforms use <scheme>://localhost.
 */
export function pageUrl(docId: number, pageIndex: number, scale: number, rev: number): string {
	const base = isWindows() ? 'http://folio.localhost' : 'folio://localhost';
	return `${base}/page/${docId}/${pageIndex}?scale=${scale.toFixed(3)}&rev=${rev}`;
}

function isWindows(): boolean {
	return typeof navigator !== 'undefined' && /Windows/i.test(navigator.userAgent);
}

export interface PageTiming {
	displayListMs: number;
	rasterMs: number;
	encodeMs: number;
}

/** Parses the X-Folio-Timing header ("dl=..;raster=..;encode=.."). */
export function parseTiming(header: string | null): PageTiming | null {
	if (!header) return null;
	const values = Object.fromEntries(
		header.split(';').map((part) => {
			const [key, value] = part.split('=');
			return [key ?? '', Number(value)];
		})
	);
	const { dl, raster, encode } = values;
	if ([dl, raster, encode].some((v) => typeof v !== 'number' || Number.isNaN(v))) return null;
	return { displayListMs: dl as number, rasterMs: raster as number, encodeMs: encode as number };
}
