// Typed wrappers over Lectrix's IPC commands and events. Payload types are generated from
// Rust (src-tauri/src/ipc.rs) by ts-rs; never edit ./generated by hand.
import { Channel, invoke } from '@tauri-apps/api/core';
import { listen, type UnlistenFn } from '@tauri-apps/api/event';

import type { AppError } from './generated/AppError';
import type { DocumentChange } from './generated/DocumentChange';
import type { DocumentInfo } from './generated/DocumentInfo';
import type { FileChangedEvent } from './generated/FileChangedEvent';
import type { MergeOutcome } from './generated/MergeOutcome';
import type { MergePlan } from './generated/MergePlan';
import type { MergeProgress } from './generated/MergeProgress';
import type { MergeRequest } from './generated/MergeRequest';
import type { OpenResult } from './generated/OpenResult';
import type { OperationInput } from './generated/OperationInput';
import type { PageText } from './generated/PageText';
import type { RecentFile } from './generated/RecentFile';
import type { RecoveredDocument } from './generated/RecoveredDocument';
import type { SaveResult } from './generated/SaveResult';
import type { SearchChunk } from './generated/SearchChunk';
import type { StartupInfo } from './generated/StartupInfo';
import type { ViewState } from './generated/ViewState';

export type {
	AppError,
	DocumentChange,
	DocumentInfo,
	FileChangedEvent,
	MergeOutcome,
	MergePlan,
	MergeProgress,
	MergeRequest,
	OpenResult,
	OperationInput,
	PageText,
	RecentFile,
	RecoveredDocument,
	SaveResult,
	SearchChunk,
	StartupInfo,
	ViewState
};
export type { Bookmark } from './generated/Bookmark';
export type { BookmarkMode } from './generated/BookmarkMode';
export type { InsertLabelMode } from './generated/InsertLabelMode';
export type { LabelMode } from './generated/LabelMode';
export type { MergePage } from './generated/MergePage';
export type { MergeReport } from './generated/MergeReport';
export type { MergeStage } from './generated/MergeStage';
export type { UnsavedSource } from './generated/UnsavedSource';
export type { BookmarkTarget } from './generated/BookmarkTarget';
export type { DocumentFlags } from './generated/DocumentFlags';
export type { DocumentState } from './generated/DocumentState';
export type { ErrorCode } from './generated/ErrorCode';
export type { ImageFormat } from './generated/ImageFormat';
export type { LabelRule } from './generated/LabelRule';
export type { LabelStyle } from './generated/LabelStyle';
export type { Outline } from './generated/Outline';
import type { ImageFormat } from './generated/ImageFormat';
export type { PageSize } from './generated/PageSize';
export type { TextLine } from './generated/TextLine';
export type { ViewDest } from './generated/ViewDest';
export type { ZoomMode } from './generated/ZoomMode';
export type { Annotation } from './generated/Annotation';
export type { AnnotationBody } from './generated/AnnotationBody';
export type { AnnotationEditInput } from './generated/AnnotationEditInput';
export type { AnnotationKind } from './generated/AnnotationKind';
export type { AnnotationProblem } from './generated/AnnotationProblem';
export type { NewAnnotationInput } from './generated/NewAnnotationInput';
export type { PageAnnotations } from './generated/PageAnnotations';
export type { RepairSummary } from './generated/RepairSummary';
export type { Appearance } from './generated/Appearance';
export type { Settings } from './generated/Settings';
export type { SettingsInput } from './generated/SettingsInput';
import type { RepairSummary } from './generated/RepairSummary';
import type { Settings } from './generated/Settings';
import type { SettingsInput } from './generated/SettingsInput';

export function isAppError(value: unknown): value is AppError {
	return (
		typeof value === 'object' && value !== null && 'message' in value && 'code' in value
	);
}

/** Turns anything thrown by a command into a user-facing error. */
export function toAppError(value: unknown): AppError {
	if (isAppError(value)) return value;
	void logError(String(value instanceof Error ? (value.stack ?? value.message) : value));
	return {
		message: 'Something went wrong.',
		suggestion: 'Try again. If it keeps happening, the app log has details.',
		code: 'general'
	};
}

export const openWithDialog = () => invoke<OpenResult[]>('open_with_dialog');
export const openStartupDocuments = () => invoke<OpenResult[]>('open_startup_documents');
export const openRecent = (index: number) => invoke<OpenResult>('open_recent', { index });
export const removeRecent = (index: number) => invoke<void>('remove_recent', { index });
export const listRecentFiles = () => invoke<RecentFile[]>('list_recent_files');
// Crash recovery (section 7): unsaved changes a crash left behind.
export const listRecovered = () => invoke<RecoveredDocument[]>('list_recovered');
export const restoreRecovered = (slots: string[]) => invoke<OpenResult[]>('restore_recovered', { slots });
export const discardRecovered = (slots: string[]) => invoke<void>('discard_recovered', { slots });
/** The user agreed to quit: this run's recovery copies are deleted. */
export const exitConfirmed = () => invoke<void>('exit_confirmed');
export const unlockDocument = (token: number, password: string) =>
	invoke<OpenResult>('unlock_document', { token, password });
export const cancelUnlock = (token: number) => invoke<void>('cancel_unlock', { token });
export const closeDocument = (id: number) => invoke<void>('close_document', { id });
export const getDocumentInfo = (id: number) => invoke<DocumentInfo>('get_document_info', { id });
/** Documents already open in Rust (the page reloaded while they were open). */
export const listOpenDocuments = () => invoke<DocumentInfo[]>('list_open_documents');
export const getPageText = (id: number, page: number) =>
	invoke<PageText>('get_page_text', { id, page });
export const searchText = (id: number, query: string, start: number, count: number) =>
	invoke<SearchChunk>('search_text', { id, query, start, count });
export const applyOperation = (id: number, operation: OperationInput) =>
	invoke<DocumentChange>('apply_operation', { id, operation });
/** A bookmark was expanded or collapsed in the panel (saved with the document, not an edit). */
export const setBookmarkOpen = (id: number, bookmark: number, open: boolean) =>
	invoke<void>('set_bookmark_open', { id, bookmark, open });
// Combining files and inserting pages (section 6.4). Sources are documents opened for
// that purpose only: not tabs. Close them with closeDocument when they are no longer needed.
export const openMergeSources = () => invoke<OpenResult[]>('open_merge_sources');
export const openInsertSource = () => invoke<OpenResult | null>('open_insert_source');
/** Sends dropped files to the Combine view (true) or into tabs. */
export const setDropTarget = (combine: boolean) => invoke<void>('set_drop_target', { combine });
export const planMerge = (sources: number[]) => invoke<MergePlan>('plan_merge', { sources });
/** Asks where to save, combines with progress, and opens the result. Null if the user cancels the dialog. */
export function executeMerge(request: MergeRequest, onProgress: (p: MergeProgress) => void) {
	const channel = new Channel<MergeProgress>();
	channel.onmessage = onProgress;
	return invoke<MergeOutcome | null>('execute_merge', { request, onProgress: channel });
}
export const cancelMerge = () => invoke<void>('cancel_merge');
export const undo = (id: number) => invoke<DocumentChange>('undo', { id });
export const redo = (id: number) => invoke<DocumentChange>('redo', { id });
export const save = (id: number) => invoke<SaveResult>('save', { id });
export const saveAs = (id: number, optimized: boolean) =>
	invoke<SaveResult | null>('save_as', { id, optimized });
export const reloadDocument = (id: number) => invoke<DocumentInfo>('reload_document', { id });
export const rememberView = (id: number, view: ViewState) =>
	invoke<void>('remember_view', { id, view });
/** What "Repair annotations" would fix (section 5.3). */
export const scanAnnotationsForRepair = (id: number) => invoke<RepairSummary>('scan_annotations_for_repair', { id });
/** Fixes it, as one undo step. */
export const repairAnnotations = (id: number) => invoke<DocumentChange>('repair_annotations', { id });
export const getSettings = () => invoke<Settings>('get_settings');
/** Stores the settings; the appearance applies to the window at once. */
export const setSettings = (settings: SettingsInput) => invoke<Settings>('set_settings', { settings });
export const appReady = () => invoke<StartupInfo>('app_ready');
export const logMetric = (name: string, ms: number) => invoke<void>('log_metric', { name, ms });
export const logError = (message: string) => invoke<void>('log_error', { message });

/** Files opened by drag-and-drop or by launching Lectrix again with a file. */
export const onDocumentsOpened = (handler: (results: OpenResult[]) => void): Promise<UnlistenFn> =>
	listen<OpenResult[]>('documents-opened', (e) => handler(e.payload));

/** Files dropped on the Combine view, opened as sources. */
export const onMergeSourcesAdded = (handler: (results: OpenResult[]) => void): Promise<UnlistenFn> =>
	listen<OpenResult[]>('merge-sources-added', (e) => handler(e.payload));

/** An open document's file was changed or removed by another program. */
export const onFileChanged = (handler: (event: FileChangedEvent) => void): Promise<UnlistenFn> =>
	listen<FileChangedEvent>('file-changed', (e) => handler(e.payload));

export interface TileRect {
	x: number;
	y: number;
	width: number;
	height: number;
}

/** The format page images are requested in (set once from StartupInfo). */
let imageFormat: ImageFormat = 'png';

export function setImageFormat(format: ImageFormat) {
	imageFormat = format;
}

/**
 * URL of a rendered page image. WebView2 (Windows) serves custom protocols as
 * http://<scheme>.localhost; other platforms use <scheme>://localhost.
 */
export function pageUrl(
	docId: number,
	pageIndex: number,
	scale: number,
	rev: number,
	tile?: TileRect,
	format: ImageFormat = imageFormat
): string {
	const base = isWindows() ? 'http://lectrix.localhost' : 'lectrix://localhost';
	let url = `${base}/page/${docId}/${pageIndex}?scale=${scale.toFixed(3)}&rev=${rev}`;
	if (tile) url += `&tile=${tile.x},${tile.y},${tile.width},${tile.height}`;
	if (format === 'png') url += '&fmt=png';
	return url;
}

function isWindows(): boolean {
	return typeof navigator !== 'undefined' && /Windows/i.test(navigator.userAgent);
}

/** A fetched page image, ready to draw once into a canvas. */
export interface PageImage {
	width: number;
	height: number;
	/** Draws the image at the canvas origin, once; then its pixels are released. */
	draw(ctx: CanvasRenderingContext2D): void;
}

/** Fetches a page or tile (raw RGBA or PNG, by the response type). */
export async function fetchPageImage(url: string, signal?: AbortSignal): Promise<PageImage> {
	const response = await fetch(url, { signal });
	if (!response.ok) throw new Error(`${response.status} ${await response.text()}`);
	if (response.headers.get('Content-Type') === 'image/png') {
		let bitmap: ImageBitmap | null = await createImageBitmap(await response.blob());
		const { width, height } = bitmap;
		return {
			width,
			height,
			draw: (ctx) => {
				if (!bitmap) return;
				ctx.drawImage(bitmap, 0, 0);
				bitmap.close();
				bitmap = null;
			}
		};
	}
	const width = Number(response.headers.get('X-Lectrix-Width'));
	const height = Number(response.headers.get('X-Lectrix-Height'));
	const buffer = await response.arrayBuffer();
	if (!width || !height || buffer.byteLength !== width * height * 4) {
		throw new Error(`unexpected image size ${width}x${height} (${buffer.byteLength} bytes)`);
	}
	// Dropped after drawing: the request's promise outlives the draw, and must not keep
	// megabytes of pixels alive next to the canvas that already holds them.
	let pixels: ImageData | null = new ImageData(new Uint8ClampedArray(buffer), width, height);
	return {
		width,
		height,
		draw: (ctx) => {
			if (pixels) ctx.putImageData(pixels, 0, 0);
			pixels = null;
		}
	};
}
