// Typed wrappers over Folio's IPC commands and events. Payload types are generated from
// Rust (src-tauri/src/ipc.rs) by ts-rs; never edit ./generated by hand.
import { invoke } from '@tauri-apps/api/core';
import { listen, type UnlistenFn } from '@tauri-apps/api/event';

import type { AppError } from './generated/AppError';
import type { DocumentChange } from './generated/DocumentChange';
import type { DocumentInfo } from './generated/DocumentInfo';
import type { FileChangedEvent } from './generated/FileChangedEvent';
import type { OpenResult } from './generated/OpenResult';
import type { OperationInput } from './generated/OperationInput';
import type { PageText } from './generated/PageText';
import type { RecentFile } from './generated/RecentFile';
import type { SaveResult } from './generated/SaveResult';
import type { SearchChunk } from './generated/SearchChunk';
import type { StartupInfo } from './generated/StartupInfo';
import type { ViewState } from './generated/ViewState';

export type {
	AppError,
	DocumentChange,
	DocumentInfo,
	FileChangedEvent,
	OpenResult,
	OperationInput,
	PageText,
	RecentFile,
	SaveResult,
	SearchChunk,
	StartupInfo,
	ViewState
};
export type { DocumentFlags } from './generated/DocumentFlags';
export type { DocumentState } from './generated/DocumentState';
export type { ErrorCode } from './generated/ErrorCode';
export type { ImageFormat } from './generated/ImageFormat';
import type { ImageFormat } from './generated/ImageFormat';
export type { PageSize } from './generated/PageSize';
export type { TextLine } from './generated/TextLine';
export type { ZoomMode } from './generated/ZoomMode';

export function isAppError(value: unknown): value is AppError {
	return (
		typeof value === 'object' && value !== null && 'message' in value && 'code' in value
	);
}

/** Turns anything thrown by a command into a user-facing error. */
export function toAppError(value: unknown): AppError {
	if (isAppError(value)) return value;
	void logError(String(value instanceof Error ? (value.stack ?? value.message) : value));
	return {
		message: 'Something went wrong.',
		suggestion: 'Try again. If it keeps happening, the app log has details.',
		code: 'general'
	};
}

export const openWithDialog = () => invoke<OpenResult[]>('open_with_dialog');
export const openStartupDocuments = () => invoke<OpenResult[]>('open_startup_documents');
export const openRecent = (index: number) => invoke<OpenResult>('open_recent', { index });
export const removeRecent = (index: number) => invoke<void>('remove_recent', { index });
export const listRecentFiles = () => invoke<RecentFile[]>('list_recent_files');
export const unlockDocument = (token: number, password: string) =>
	invoke<OpenResult>('unlock_document', { token, password });
export const cancelUnlock = (token: number) => invoke<void>('cancel_unlock', { token });
export const closeDocument = (id: number) => invoke<void>('close_document', { id });
export const getDocumentInfo = (id: number) => invoke<DocumentInfo>('get_document_info', { id });
export const getPageText = (id: number, page: number) =>
	invoke<PageText>('get_page_text', { id, page });
export const searchText = (id: number, query: string, start: number, count: number) =>
	invoke<SearchChunk>('search_text', { id, query, start, count });
export const applyOperation = (id: number, operation: OperationInput) =>
	invoke<DocumentChange>('apply_operation', { id, operation });
export const undo = (id: number) => invoke<DocumentChange>('undo', { id });
export const redo = (id: number) => invoke<DocumentChange>('redo', { id });
export const save = (id: number) => invoke<SaveResult>('save', { id });
export const saveAs = (id: number, optimized: boolean) =>
	invoke<SaveResult | null>('save_as', { id, optimized });
export const reloadDocument = (id: number) => invoke<DocumentInfo>('reload_document', { id });
export const rememberView = (id: number, view: ViewState) =>
	invoke<void>('remember_view', { id, view });
export const appReady = () => invoke<StartupInfo>('app_ready');
export const logMetric = (name: string, ms: number) => invoke<void>('log_metric', { name, ms });
export const logError = (message: string) => invoke<void>('log_error', { message });

/** Files opened by drag-and-drop or by launching Folio again with a file. */
export const onDocumentsOpened = (handler: (results: OpenResult[]) => void): Promise<UnlistenFn> =>
	listen<OpenResult[]>('documents-opened', (e) => handler(e.payload));

/** An open document's file was changed or removed by another program. */
export const onFileChanged = (handler: (event: FileChangedEvent) => void): Promise<UnlistenFn> =>
	listen<FileChangedEvent>('file-changed', (e) => handler(e.payload));

export interface TileRect {
	x: number;
	y: number;
	width: number;
	height: number;
}

/** The format page images are requested in (set once from StartupInfo). */
let imageFormat: ImageFormat = 'rgba';

export function setImageFormat(format: ImageFormat) {
	imageFormat = format;
}

/**
 * URL of a rendered page image. WebView2 (Windows) serves custom protocols as
 * http://<scheme>.localhost; other platforms use <scheme>://localhost.
 */
export function pageUrl(
	docId: number,
	pageIndex: number,
	scale: number,
	rev: number,
	tile?: TileRect,
	format: ImageFormat = imageFormat
): string {
	const base = isWindows() ? 'http://folio.localhost' : 'folio://localhost';
	let url = `${base}/page/${docId}/${pageIndex}?scale=${scale.toFixed(3)}&rev=${rev}`;
	if (tile) url += `&tile=${tile.x},${tile.y},${tile.width},${tile.height}`;
	if (format === 'png') url += '&fmt=png';
	return url;
}

function isWindows(): boolean {
	return typeof navigator !== 'undefined' && /Windows/i.test(navigator.userAgent);
}

/** A fetched page image, ready to draw once into a canvas. */
export interface PageImage {
	width: number;
	height: number;
	/** Draws the image at the canvas origin, once; then its pixels are released. */
	draw(ctx: CanvasRenderingContext2D): void;
}

/** Fetches a page or tile (raw RGBA or PNG, by the response type). */
export async function fetchPageImage(url: string, signal?: AbortSignal): Promise<PageImage> {
	const response = await fetch(url, { signal });
	if (!response.ok) throw new Error(`${response.status} ${await response.text()}`);
	if (response.headers.get('Content-Type') === 'image/png') {
		let bitmap: ImageBitmap | null = await createImageBitmap(await response.blob());
		const { width, height } = bitmap;
		return {
			width,
			height,
			draw: (ctx) => {
				if (!bitmap) return;
				ctx.drawImage(bitmap, 0, 0);
				bitmap.close();
				bitmap = null;
			}
		};
	}
	const width = Number(response.headers.get('X-Folio-Width'));
	const height = Number(response.headers.get('X-Folio-Height'));
	const buffer = await response.arrayBuffer();
	if (!width || !height || buffer.byteLength !== width * height * 4) {
		throw new Error(`unexpected image size ${width}x${height} (${buffer.byteLength} bytes)`);
	}
	// Dropped after drawing: the request's promise outlives the draw, and must not keep
	// megabytes of pixels alive next to the canvas that already holds them.
	let pixels: ImageData | null = new ImageData(new Uint8ClampedArray(buffer), width, height);
	return {
		width,
		height,
		draw: (ctx) => {
			if (pixels) ctx.putImageData(pixels, 0, 0);
			pixels = null;
		}
	};
}
