//! Annotation payloads (AGENTS.md sections 5 and 6.5). TypeScript types are generated by
//! ts-rs like the rest of `ipc`.

use serde::{Deserialize, Serialize};
use ts_rs::TS;

use pdf_core::annot::read::{AnnotationInfo, Problem};
use pdf_core::annot::repair::RepairScan;
use pdf_core::annot::{self as core, Kind, MarkupKind, Rgb};
use pdf_core::geometry::{Point, Rect};

use crate::ipc::AppError;

/// The annotation types Lectrix creates.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub enum AnnotationKind {
    Highlight,
    Underline,
    StrikeOut,
    Squiggly,
    Note,
    Ink,
    FreeText,
}

impl From<Kind> for AnnotationKind {
    fn from(k: Kind) -> Self {
        match k {
            Kind::Highlight => AnnotationKind::Highlight,
            Kind::Underline => AnnotationKind::Underline,
            Kind::StrikeOut => AnnotationKind::StrikeOut,
            Kind::Squiggly => AnnotationKind::Squiggly,
            Kind::Note => AnnotationKind::Note,
            Kind::Ink => AnnotationKind::Ink,
            Kind::FreeText => AnnotationKind::FreeText,
        }
    }
}

/// What "Repair annotations" would fix (section 5.3), or can't.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub enum AnnotationProblem {
    MissingAppearance,
    QuadOrder,
    RectTooSmall,
    MissingName,
    MissingFlags,
    MissingModified,
    MissingPage,
    /// Repair can't fix this one.
    MalformedQuads,
}

impl From<Problem> for AnnotationProblem {
    fn from(p: Problem) -> Self {
        match p {
            Problem::MissingAppearance => AnnotationProblem::MissingAppearance,
            Problem::QuadOrder => AnnotationProblem::QuadOrder,
            Problem::RectTooSmall => AnnotationProblem::RectTooSmall,
            Problem::MissingName => AnnotationProblem::MissingName,
            Problem::MissingFlags => AnnotationProblem::MissingFlags,
            Problem::MissingModified => AnnotationProblem::MissingModified,
            Problem::MissingPage => AnnotationProblem::MissingPage,
            Problem::MalformedQuads => AnnotationProblem::MalformedQuads,
        }
    }
}

/// One annotation for the list and the page overlay. Geometry is in points, view space at
/// zoom 1 (origin top-left of the visible page, y down), like text geometry.
#[derive(Debug, Clone, Serialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct Annotation {
    /// Object number; 0 when the annotation can't be edited (not an indirect object).
    pub id: u32,
    pub page: u32,
    /// The PDF subtype ("Highlight", "Square", "Stamp"...).
    pub subtype: String,
    /// Set for the types Lectrix creates.
    pub kind: Option<AnnotationKind>,
    /// `/Rect`: x0, y0, x1, y1.
    pub rect: [f32; 4],
    /// What moving and resizing act on, and where a note's icon is shown.
    pub bounds: [f32; 4],
    /// Text-markup quads, 8 numbers each (ul, ur, ll, lr).
    pub quads: Vec<f32>,
    /// Ink strokes: x, y, x, y...
    pub ink: Vec<Vec<f32>>,
    /// `#rrggbb` (a text box: its text colour).
    pub color: Option<String>,
    pub opacity: f32,
    /// Note text (a text box: the text in it).
    pub contents: String,
    pub author: String,
    /// Milliseconds since the Unix epoch.
    #[ts(type = "number | null")]
    pub created: Option<i64>,
    #[ts(type = "number | null")]
    pub modified: Option<i64>,
    /// Id of the annotation this one replies to.
    pub reply_to: Option<u32>,
    /// Not drawn (Hidden or NoView flag).
    pub hidden: bool,
    pub width: Option<f32>,
    pub font_size: Option<f32>,
    /// Empty when nothing needs repair.
    pub problems: Vec<AnnotationProblem>,
}

/// The annotations of one page.
#[derive(Debug, Clone, Serialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct PageAnnotations {
    pub page: u32,
    pub annotations: Vec<Annotation>,
}

fn rect4(r: Rect) -> [f32; 4] {
    [r.x0 as f32, r.y0 as f32, r.x1 as f32, r.y1 as f32]
}

pub fn hex(c: Rgb) -> String {
    let ch = |v: f32| (v.clamp(0.0, 1.0) * 255.0).round() as u8;
    format!("#{:02x}{:02x}{:02x}", ch(c.r), ch(c.g), ch(c.b))
}

pub fn parse_hex(s: &str) -> Result<Rgb, AppError> {
    let bad = || AppError::new("That colour isn't valid.", Some("Pick another colour."));
    let s = s.strip_prefix('#').unwrap_or(s);
    if s.len() != 6 || !s.is_ascii() {
        return Err(bad());
    }
    let ch = |i: usize| {
        u8::from_str_radix(&s[i..i + 2], 16)
            .map(|v| f32::from(v) / 255.0)
            .map_err(|_| bad())
    };
    Ok(Rgb {
        r: ch(0)?,
        g: ch(2)?,
        b: ch(4)?,
    })
}

impl From<AnnotationInfo> for Annotation {
    fn from(a: AnnotationInfo) -> Self {
        Annotation {
            id: a.id,
            page: u32::try_from(a.page).unwrap_or(u32::MAX),
            kind: a.kind.map(Into::into),
            rect: rect4(a.rect),
            bounds: rect4(a.bounds),
            quads: a
                .quads
                .iter()
                .flat_map(|q| [q.ul, q.ur, q.ll, q.lr])
                .flat_map(|p| [p.x as f32, p.y as f32])
                .collect(),
            ink: a
                .ink
                .iter()
                .map(|s| s.iter().flat_map(|p| [p.x as f32, p.y as f32]).collect())
                .collect(),
            color: a.color.map(hex),
            opacity: a.opacity,
            contents: a.contents,
            author: a.author,
            created: a.created,
            modified: a.modified,
            reply_to: a.reply_to,
            hidden: a.hidden,
            width: a.width.map(|w| w as f32),
            font_size: a.font_size.map(|s| s as f32),
            problems: a.problems.into_iter().map(Into::into).collect(),
            subtype: a.subtype,
        }
    }
}

/// Pages that have annotations, from every page's list.
pub fn pages(all: Vec<Vec<AnnotationInfo>>) -> Vec<PageAnnotations> {
    all.into_iter()
        .enumerate()
        .filter(|(_, list)| !list.is_empty())
        .map(|(page, list)| page_annotations(page, list))
        .collect()
}

/// Pages whose annotations changed (also pages that have none left).
pub fn changed(list: Vec<(usize, Vec<AnnotationInfo>)>) -> Vec<PageAnnotations> {
    list.into_iter()
        .map(|(page, list)| page_annotations(page, list))
        .collect()
}

fn page_annotations(page: usize, list: Vec<AnnotationInfo>) -> PageAnnotations {
    PageAnnotations {
        page: u32::try_from(page).unwrap_or(u32::MAX),
        annotations: list.into_iter().map(Into::into).collect(),
    }
}

/// What a new annotation is (geometry in view space at zoom 1).
#[derive(Debug, Clone, Deserialize, TS)]
#[serde(
    tag = "tool",
    rename_all = "camelCase",
    rename_all_fields = "camelCase"
)]
#[ts(export)]
pub enum AnnotationBody {
    /// Highlight, underline, strikeout or squiggly over selected text: character ranges
    /// of the page's text lines, as `get_page_text` numbers them. Rust makes the quads.
    TextMarkup {
        kind: AnnotationKind,
        ranges: Vec<TextRangeInput>,
        note: Option<String>,
    },
    /// Highlight, underline, strikeout or squiggly over an area: `quads` 8 numbers each.
    Markup {
        kind: AnnotationKind,
        quads: Vec<f32>,
        note: Option<String>,
    },
    /// A sticky note whose icon's top-left corner is at (x, y).
    Note { x: f32, y: f32, text: String },
    /// Strokes: x, y, x, y...
    Ink { strokes: Vec<Vec<f32>>, width: f32 },
    /// A text box: x0, y0, x1, y1; its height grows to fit the text.
    FreeText {
        rect: [f32; 4],
        text: String,
        font_size: f32,
    },
}

/// Characters `start..end` (code points) of text line `line`.
#[derive(Debug, Clone, Copy, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct TextRangeInput {
    pub line: u32,
    pub start: u32,
    pub end: u32,
}

#[derive(Debug, Clone, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct NewAnnotationInput {
    pub page: u32,
    /// `#rrggbb`.
    pub color: String,
    pub opacity: f32,
    pub body: AnnotationBody,
}

/// A change to one annotation; null leaves a property as it is.
#[derive(Debug, Clone, Default, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct AnnotationEditInput {
    #[ts(optional)]
    pub color: Option<String>,
    #[ts(optional)]
    pub opacity: Option<f32>,
    /// Note text (a text box: its text). Empty removes a note.
    #[ts(optional)]
    pub contents: Option<String>,
    #[ts(optional)]
    pub author: Option<String>,
    /// Move or resize: x0, y0, x1, y1 (see `Annotation::bounds`).
    #[ts(optional)]
    pub bounds: Option<[f32; 4]>,
    #[ts(optional)]
    pub width: Option<f32>,
    #[ts(optional)]
    pub font_size: Option<f32>,
    /// Turn text markup into another text-markup type.
    #[ts(optional)]
    pub kind: Option<AnnotationKind>,
}

fn rect_from(v: [f32; 4]) -> Rect {
    Rect::new(
        f64::from(v[0]),
        f64::from(v[1]),
        f64::from(v[2]),
        f64::from(v[3]),
    )
}

fn points(values: &[f32]) -> Vec<Point> {
    values
        .as_chunks::<2>()
        .0
        .iter()
        .map(|[x, y]| Point::new(f64::from(*x), f64::from(*y)))
        .collect()
}

/// The text-markup kind `kind` is, if it is one.
fn markup_kind(kind: AnnotationKind) -> Option<MarkupKind> {
    Some(match kind {
        AnnotationKind::Highlight => MarkupKind::Highlight,
        AnnotationKind::Underline => MarkupKind::Underline,
        AnnotationKind::StrikeOut => MarkupKind::StrikeOut,
        AnnotationKind::Squiggly => MarkupKind::Squiggly,
        _ => return None,
    })
}

impl NewAnnotationInput {
    /// The annotation, written by `author` (the name from Settings).
    pub fn into_core(self, author: &str) -> Result<core::NewAnnotation, AppError> {
        let bad = || AppError::new("That annotation can't be made.", None);
        let markup_kind = |kind| markup_kind(kind).ok_or_else(bad);
        let body = match self.body {
            AnnotationBody::TextMarkup { kind, ranges, note } => core::Body::TextMarkup {
                kind: markup_kind(kind)?,
                ranges: ranges
                    .iter()
                    .map(|r| pdf_core::text::TextRange {
                        line: r.line as usize,
                        start: r.start as usize,
                        end: r.end as usize,
                    })
                    .collect(),
                note: note.filter(|n| !n.is_empty()),
            },
            AnnotationBody::Markup { kind, quads, note } => {
                let kind = markup_kind(kind)?;
                let quads = core::quads::quads_from_array(
                    &quads.iter().map(|v| f64::from(*v)).collect::<Vec<_>>(),
                )
                .ok_or_else(bad)?;
                core::Body::Markup {
                    kind,
                    quads,
                    note: note.filter(|n| !n.is_empty()),
                }
            }
            AnnotationBody::Note { x, y, text } => core::Body::Note {
                at: Point::new(f64::from(x), f64::from(y)),
                text,
            },
            AnnotationBody::Ink { strokes, width } => core::Body::Ink {
                strokes: strokes.iter().map(|s| points(s)).collect(),
                width: f64::from(width),
            },
            AnnotationBody::FreeText {
                rect,
                text,
                font_size,
            } => core::Body::FreeText {
                rect: rect_from(rect),
                text,
                font_size: f64::from(font_size),
            },
        };
        Ok(core::NewAnnotation {
            page: self.page as usize,
            body,
            color: parse_hex(&self.color)?,
            opacity: self.opacity,
            author: author.to_owned(),
        })
    }
}

impl AnnotationEditInput {
    pub fn into_core(self) -> Result<core::AnnotationEdit, AppError> {
        Ok(core::AnnotationEdit {
            color: self.color.as_deref().map(parse_hex).transpose()?,
            opacity: self.opacity,
            contents: self.contents,
            author: self.author,
            bounds: self.bounds.map(rect_from),
            width: self.width.map(f64::from),
            font_size: self.font_size.map(f64::from),
            kind: self
                .kind
                .map(|k| {
                    markup_kind(k).ok_or_else(|| {
                        AppError::new("Only text markup can be turned into another type.", None)
                    })
                })
                .transpose()?,
        })
    }
}

#[derive(Debug, Clone, Serialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct ProblemCount {
    pub problem: AnnotationProblem,
    /// Annotations with this problem.
    pub count: u32,
}

/// What a repair scan found (section 5.3).
#[derive(Debug, Clone, Serialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct RepairSummary {
    pub counts: Vec<ProblemCount>,
    /// Annotations repair would change.
    pub fixable: u32,
    /// Annotations with problems repair can't fix.
    pub unfixable: u32,
}

impl From<RepairScan> for RepairSummary {
    fn from(s: RepairScan) -> Self {
        let n = |v: usize| u32::try_from(v).unwrap_or(u32::MAX);
        RepairSummary {
            counts: s
                .counts
                .into_iter()
                .map(|(p, c)| ProblemCount {
                    problem: p.into(),
                    count: n(c),
                })
                .collect(),
            fixable: n(s.fixable),
            unfixable: n(s.unfixable),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn colours_round_trip() {
        let c = parse_hex("#1a73e8").unwrap();
        assert_eq!(hex(c), "#1a73e8");
        assert_eq!(hex(parse_hex("FFEB3B").unwrap()), "#ffeb3b");
        assert!(parse_hex("#12345").is_err());
        assert!(parse_hex("#gggggg").is_err());
        assert!(parse_hex("#ééé").is_err());
    }

    #[test]
    fn new_annotations_take_the_settings_author() {
        let input: NewAnnotationInput = serde_json::from_str(
            r##"{"page":2,"color":"#ffeb3b","opacity":0.5,
                "body":{"tool":"markup","kind":"highlight","quads":[0,0,10,0,0,5,10,5],"note":""}}"##,
        )
        .unwrap();
        let core = input.into_core("Ada").unwrap();
        assert_eq!(core.author, "Ada");
        assert_eq!(core.page, 2);
        assert!(matches!(core.body, core::Body::Markup { note: None, .. }));

        let bad: NewAnnotationInput = serde_json::from_str(
            r##"{"page":0,"color":"#ffeb3b","opacity":1,
                "body":{"tool":"markup","kind":"note","quads":[0,0,10,0,0,5,10,5]}}"##,
        )
        .unwrap();
        assert!(bad.into_core("Ada").is_err());

        let ink: NewAnnotationInput = serde_json::from_str(
            r##"{"page":0,"color":"#000000","opacity":1,
                "body":{"tool":"ink","strokes":[[1,2,3,4,5,6]],"width":2}}"##,
        )
        .unwrap();
        match ink.into_core("Ada").unwrap().body {
            core::Body::Ink { strokes, .. } => assert_eq!(strokes[0].len(), 3),
            other => panic!("{other:?}"),
        }
    }
}
